---

# CISCO auth params
ansible_network_os: "ios"
ansible_user: "hpc"
ansible_connection: "network_cli"
ansible_become: "yes"
ansible_become_method: enable

# CISCO user password
cisco_password: '{{ readonly_password }}'

# CISCO enable password
ansible_become_password: '{{ admin_password }}'