---

# CISCO auth params
ansible_network_os: "ios"
ansible_user: "hpc"
ansible_connection: "network_cli"
ansible_become: "yes"
ansible_become_method: enable

# CISCO user password
ansible_ssh_pass: '{{ readonly_password }}'

# CISCO enable password
ansible_become_password: '{{ admin_password }}'

vlans:
  - { name: 'LAN',             id: '1' }
  - { name: 'management',      id: '2' }
  - { name: 'WAN',             id: '3' }
  - { name: 'Wi-fi',           id: '4' }