---

- name: Deploy Gitlab
  community.docker.docker_compose:
    project_name: 'gitlab'
    definition:
      version: '3'
      services:
        web:
          image: 'gitlab/gitlab-ee:latest'
          restart: always
          hostname: '{{ external_subdomains.gitlab }}.{{ domain_name }}'
          container_name: gitlab
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://{{ external_subdomains.gitlab }}.{{ domain_name }}'
              nginx['listen_https'] = false
              nginx['listen_port'] = 80
              nginx['redirect_http_to_https'] = false
              letsencrypt['enable'] = false
              gitlab_rails['initial_root_password'] = '{{ admin_password }}'
              gitlab_rails['gitlab_shell_ssh_port'] = 5001
              gitlab_rails['gitlab_email_enabled'] = false
              gitlab_rails['ldap_enabled'] = true
              gitlab_rails['ldap_servers'] = {
                'main' => {
                  'label' => 'LDAP',
                  'host' =>  '{{ control_aliases.ldap }}.{{ domain_name }}',
                  'port' => 636,
                  'uid' => 'uid',
                  'encryption' => 'simple_tls',
                  'verify_certificates' => false,
                  'active_directory' => false,
                  'bind_dn' => 'cn=readonly,{{ domain_ldap }}',
                  'password' => '{{ readonly_password }}',
                  'base' => '{{ domain_ldap }}',
                  'allow_username_or_email_login' => false,
                  'attributes' => {
                    'username' => ['uid'],
                    'email' => ['mail'],
                    'name' => 'cn',
                    'first_name' => 'givenName',
                    'last_name' => 'sn'
                  }
                }
              }
          ports:
            - '4001:80'
            - '5001:22'
          volumes:
            - '/docker/gitlab/config:/etc/gitlab'
            - '/docker/gitlab/logs:/var/log/gitlab'
            - '/docker/gitlab/data:/var/opt/gitlab'
    
- name: Ensure existance of certificates directory
  file:
    path: "/docker/certbot/conf/live/{{ external_subdomains.gitlab }}.{{ domain_name }}"
    state: directory

- name: Check the existence of SLL certificate
  shell: test -e "/docker/certbot/conf/live/{{ external_subdomains.gitlab }}.{{ domain_name }}/privkey.pem"
  register: cert_exists
  ignore_errors: true
  changed_when: false

- name: Generate dummy certificates
  shell: |
    openssl req -x509 -nodes -newkey rsa:4096 -days 1 -keyout "/docker/certbot/conf/live/{{ external_subdomains.gitlab }}.{{ domain_name }}/privkey.pem" -out "/docker/certbot/conf/live/{{ external_subdomains.gitlab }}.{{ domain_name }}/fullchain.pem" -subj '/CN=localhost'
  when: cert_exists.rc != 0
  
- name: Generate NGINX reverse proxy template
  template:
    src: gitlab.conf.j2
    dest: /docker/nginx/sites-enabled/gitlab.conf
    mode: 0600
  notify: Restart NGINX

- name: Sync handlers
  meta: flush_handlers

- name: Renew certs
  shell: |
    rm -f /docker/certbot/conf/live/"{{ external_subdomains.lam }}.{{ domain_name }}"/*
    docker exec certbot certbot certonly --webroot -w /var/www/certbot -d "{{ external_subdomains.gitlab }}.{{ domain_name }}" --rsa-key-size 4096 --agree-tos --force-renewal --email "{{ letsencrypt_email }}" -n
  failed_when: False
  when: ((inventory_hostname in groups.control_nodes) and
        (cert_exists.rc != 0))

- name: Sync handlers
  meta: flush_handlers

- name: Wait for Gitlab to startup
  local_action:
    module: uri
    url: "https://{{ external_subdomains.gitlab }}.{{ domain_name }}"
    follow_redirects: all
    method: GET
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- name: Generate random Gitlab API token
  set_fact:
    token: "{{ lookup('community.general.random_string', length=20, base64=True) }}"

- name: Set Gitlab API key and disable signup
  shell: |
    docker exec gitlab gitlab-rails runner '
    ApplicationSetting.last.update(signup_enabled: false)
    User.find_by_username("root").personal_access_tokens.all.each { |t| if t.name == "LDAP sync token" then t.revoke! end }
    token = User.find_by_username("root").personal_access_tokens.create(scopes: [:api, :sudo], name: "LDAP sync token")
    token.set_token("{{ token }}")
    token.save!'
  failed_when: false
  changed_when: false

- name: Install Gitlab LDAP sync script dnf dependencies
  dnf:
    name: ['gcc-toolset-11', 'python3-devel', 'openldap-devel']
    state: latest

- name: Install Gitlab LDAP sync script pip dependencies
  pip:
    name: ['python-gitlab', 'python-ldap']

- name: Copy Gitlab LDAP sync script
  copy:
    src: gitlab-ldap-sync.py
    dest: /root/gitlab-ldap-sync.py
    mode: 700

- name: Generate Gitlab LDAP sync config file
  template:
    src: gitlab-ldap-sync.json.j2
    dest: /root/gitlab-ldap-sync.json
    mode: 400

- name: Enable sync script to run every minute
  cron:
    name: "Sync Gitlab with LDAP"
    minute: '*/30'
    user: root
    job: "/root/gitlab-ldap-sync.py"
    cron_file: gitlab_ldap