---

- name: Copy global NGINX configuration
  copy:
    src: nginx
    dest: /docker/
    mode: 750
    
- name: Ensure existance of NGINX sites directory
  file:
    path: /docker/nginx/sites-enabled
    state: directory

- name: Deploy NGINX
  community.docker.docker_compose:
    project_name: 'nginx'
    definition:
      version: '3'
      services:
        nginx:
            image: nginx:stable
            container_name: nginx
            volumes:
                - /docker/nginx:/etc/nginx/
                - /docker/certbot/conf:/etc/letsencrypt
                - /docker/certbot/www:/var/www/certbot
                - /etc/localtime:/etc/localtime:ro
            network_mode: host
            restart: always
            command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        certbot:
            image: certbot/certbot:latest
            container_name: certbot
            volumes:
                - /docker/certbot/conf:/etc/letsencrypt
                - /docker/certbot/www:/var/www/certbot
                - /etc/localtime:/etc/localtime:ro
            entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

- name: Allow HTTPS traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  with_items:
    - http
    - https
  notify: Reload firewalld

- name: Sync handlers
  meta: flush_handlers