---

- name: Control nodes setup
  hosts: control_nodes
  become: True
  roles:
  - network
  - chrony
  - dns
  - dhcp
  - pxe
  - nas
  - docker
  - slurm
  - auth
  - registry
  - nginx
  - zabbix
  - hass
  - gitlab