---
  
- name: Web cluster nodes setup
  hosts: cpu_nodes
  become: True
  ignore_unreachable: True
  roles:
  - network
  - chrony
  - nas
  - docker

- name: Compute cluster setup 
  hosts: gpu_nodes
  become: True
  ignore_unreachable: True
  roles:
  - network
  - chrony
  - nas
  - docker
  - auth
  - slurm