---

- name: Control nodes setup
  hosts: control_nodes
  become: True
  roles:
  - network      # General network services
  - chrony       # Time sync service
  - dns          # BIND9 DNS service
  - dhcp         # DHCP service