---

- name: Create VLANs
  ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.id }}"
    state: merged
  with_items:
    - "{{ vlans }}"

- name: Manage access mode interfaces
  ios_command:
    commands:
    - configure terminal
    - "default {{ item.name }}"
    - "interface {{ item.name }}"
    - switchport mode access
    - "switchport access vlan {{ item.vlan }}"
    - end
  with_items:
  - "{{ switched_interfaces }}"
  when: item.mode == "access"

- name: Manage trunk mode interfaces
  ios_command:
    commands:
    - configure terminal
    - "default {{ item.name }}"
    - "interface {{ item.name }}"
    - switchport mode trunk
    - end
  with_items:
  - "{{ switched_interfaces }}"
  when: item.mode == "trunk"

- name: Manage disabled interfaces
  ios_command:
    commands:
    - configure terminal
    - "interface {{ item.name }}"
    - shutdown
    - end
  with_items:
  - "{{ switched_interfaces }}"
  when: item.mode == "disable"