---

- name: Restart SSSD
  service:
    name: sssd
    state: restarted
  
- name: Restart SSH
  service:
    name: sshd
    state: restarted
  
- name: Run authselect
  shell: authselect select sssd with-mkhomedir --force
  
- name: Reload firewalld
  shell: 'firewall-cmd --reload'
  
- name: Restart NGINX
  shell: docker restart nginx