---

- name: Disable mounting swap partition on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap partition
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add Kubernetes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: 0664
    owner: root
    group: root

- name: Install Kubernetes
  dnf:
    name: ['kubelet', 'kubeadm', 'kubectl']
    disable_gpg_check: yes
    state: latest

- name: Allow k8s traffic
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: private
    permanent: yes
    state: enabled
  with_items:
    - '6443/tcp'
    - '2379-2380/tcp'
    - '10250/tcp'
    - '10251/tcp'
    - '10252/tcp'
    - '10255/tcp'
    - '8472/udp'
  when: inventory_hostname in groups.control_nodes
  notify: Reload firewalld

- name: Start and enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ networks.private.cidr | ipaddr('address') }}" --node-name "{{ inventory_hostname }}" --pod-network-cidr=192.168.0.0/16
  when: inventory_hostname in groups.control_nodes


