---

- name: Disable mounting swap partition on boot
  ansible.posix.mount:
    fstype: swap
    state: absent

- name: Disable swap partition
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add Kubernetes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: 0664
    owner: root
    group: root

- name: Install Kubernetes
  dnf:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: latest

- name: Start and enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  when: inventory_hostname in groups.control_nodes


