---

interfaces:
  - { name: "management", type: "ethernet", mac: "03:00:00:00:00:01", subnet: "private" }

switched_interfaces:
- { name: "Gi1/0/1",  mode: "access", vlan: "1" } # gpu-node-0
- { name: "Gi1/0/2",  mode: "access", vlan: "1" } # cpu-node-0
- { name: "Gi1/0/3",  mode: "access", vlan: "1" } # k8s-node-0
- { name: "Gi1/0/4",  mode: "access", vlan: "1" } # Goes to Mellanox MGMT port
- { name: "Gi1/0/5",  mode: "access", vlan: "2" } # Goes to management passive switches
- { name: "Gi1/0/6",  mode: "trunk"             } # Goes to cisco-0
- { name: "Te1/0/1",  mode: "trunk"             } # Control node
- { name: "Te1/0/2",  mode: "access", vlan: "1" } # NAS