---

- name: Install NFS and iSCSI
  dnf:
    name: ['nfs-utils', 'iscsi-initiator-utils']
    state: latest
  
- name: Create iSCSI mount directory
  file:
    path: /export
    state: directory
  when: inventory_hostname in groups.control_nodes

- name: Discover default NAS target
  open_iscsi:
    show_nodes: yes
    discover: yes
    portal: "{{ (networks.private.cidr | ipaddr('address')) | ipmath(69) }}"
  register: discovery
  when: inventory_hostname in groups.control_nodes

- name: Login to discovered target
  open_iscsi:
    login: yes
    target: "{{ discovery.nodes[0] }}"
  register: device
  when: inventory_hostname in groups.control_nodes

- name: Mount
  ansible.posix.mount:
    path: /export
    src: "{{ device.devicenodes[0] }}"
    opts: _netdev,rw
    fstype: ext4
    boot: yes
    state: mounted
  when: inventory_hostname in groups.control_nodes

- name: Ensure existance of home directory
  file:
    path: /export/home
    state: directory
    mode: 0755
  when: inventory_hostname in groups.control_nodes

- name: Ensure existance of shared directory
  file:
    path: /export/shared
    state: directory
    mode: 0777
  when: inventory_hostname in groups.control_nodes

- name: Ensure existance of software directory
  file:
    path: /export/software
    state: directory
    mode: 0755
  when: inventory_hostname in groups.control_nodes

- name: Add NFS exports
  lineinfile:
    path: /etc/exports
    regexp: "^/export/{{ item }}.*"
    line: "/export/{{ item }}\t{{ networks.private.cidr }}(rw,sync,no_root_squash)"
  with_items:
    - home
    - software
    - shared
  when: inventory_hostname in groups.control_nodes
  notify: Update NFS exports

- name: Sync handlers
  meta: flush_handlers
  
- name: Allow NFS traffic
  ansible.posix.firewalld:
    service: nfs3
    zone: private
    permanent: yes
    state: enabled
  when: inventory_hostname in groups.control_nodes
  notify: Reload firewalld
  
- name: Start and enable NFS service
  service:
    name: nfs-server
    state: started
    enabled: true
  when: inventory_hostname in groups.control_nodes

- name: Ensure existance of NFS mount directories
  file:
    path: /{{ item }}
    state: directory
  with_items:
    - home
    - software
    - shared

- name: Mount NFS share
  ansible.posix.mount:
    path: /{{ item }}
    src: "{{ control_aliases.nfs }}.{{ domain_name }}:/export/{{ item }}"
    opts: rw,sync,hard
    fstype: nfs
    boot: yes
    state: mounted
  with_items:
    - home
    - software
    - shared